<?php

use Illuminate\Database\Seeder;
use App\Models\ShopGridVariation;

class ShopGridVariationsTable extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
     public function run()
     {

         foreach ($this->array_data() as $arr) {

             $data = [
                 'shop_grid_id' => $arr['shop_grid_id'],
                 'name' => $arr['name'],
                 'hex' => $arr['hex']
             ];

             if (ShopGridVariation::where('name', '=', $arr['name'])->where('shop_grid_id', '=', $arr['shop_grid_id'])->where('hex', '=', $arr['hex'])->count()) {
                 $grid = ShopGridVariation::where('name', '=', $arr['name'])->where('shop_grid_id', '=', $arr['shop_grid_id'])->where('hex', '=', $arr['hex'])->first();
                 $grid->update($data);
             } else {
                 ShopGridVariation::create($data);
             }

         }

     }

     public function array_data()
     {
         return [
            ['shop_grid_id' => '1','name' => 'Feminino','hex' => NULL],
            ['shop_grid_id' => '1','name' => 'Masculino','hex' => NULL],
            ['shop_grid_id' => '4','name' => '10','hex' => NULL],
            ['shop_grid_id' => '4','name' => '11','hex' => NULL],
            ['shop_grid_id' => '4','name' => '12','hex' => NULL],
            ['shop_grid_id' => '4','name' => '13','hex' => NULL],
            ['shop_grid_id' => '4','name' => '14','hex' => NULL],
            ['shop_grid_id' => '4','name' => '15','hex' => NULL],
            ['shop_grid_id' => '4','name' => '16','hex' => NULL],
            ['shop_grid_id' => '4','name' => '17','hex' => NULL],
            ['shop_grid_id' => '4','name' => '18','hex' => NULL],
            ['shop_grid_id' => '4','name' => '19','hex' => NULL],
            ['shop_grid_id' => '4','name' => '20','hex' => NULL],
            ['shop_grid_id' => '4','name' => '21','hex' => NULL],
            ['shop_grid_id' => '4','name' => '22','hex' => NULL],
            ['shop_grid_id' => '4','name' => '23','hex' => NULL],
            ['shop_grid_id' => '4','name' => '24','hex' => NULL],
            ['shop_grid_id' => '4','name' => '25','hex' => NULL],
            ['shop_grid_id' => '4','name' => '26','hex' => NULL],
            ['shop_grid_id' => '4','name' => '27','hex' => NULL],
            ['shop_grid_id' => '4','name' => '28','hex' => NULL],
            ['shop_grid_id' => '4','name' => '29','hex' => NULL],
            ['shop_grid_id' => '4','name' => '30','hex' => NULL],
            ['shop_grid_id' => '4','name' => '31','hex' => NULL],
            ['shop_grid_id' => '4','name' => '32','hex' => NULL],
            ['shop_grid_id' => '4','name' => '33','hex' => NULL],
            ['shop_grid_id' => '4','name' => '34','hex' => NULL],
            ['shop_grid_id' => '4','name' => '35','hex' => NULL],
            ['shop_grid_id' => '4','name' => '36','hex' => NULL],
            ['shop_grid_id' => '4','name' => '37','hex' => NULL],
            ['shop_grid_id' => '4','name' => '38','hex' => NULL],
            ['shop_grid_id' => '4','name' => '39','hex' => NULL],
            ['shop_grid_id' => '4','name' => '40','hex' => NULL],
            ['shop_grid_id' => '5','name' => '34','hex' => NULL],
            ['shop_grid_id' => '5','name' => '36','hex' => NULL],
            ['shop_grid_id' => '5','name' => '38','hex' => NULL],
            ['shop_grid_id' => '5','name' => '40','hex' => NULL],
            ['shop_grid_id' => '5','name' => '42','hex' => NULL],
            ['shop_grid_id' => '5','name' => '44','hex' => NULL],
            ['shop_grid_id' => '5','name' => '46','hex' => NULL],
            ['shop_grid_id' => '5','name' => '48','hex' => NULL],
            ['shop_grid_id' => '5','name' => '50','hex' => NULL],
            ['shop_grid_id' => '5','name' => '52','hex' => NULL],
            ['shop_grid_id' => '5','name' => '54','hex' => NULL],
            ['shop_grid_id' => '5','name' => '56','hex' => NULL],
            ['shop_grid_id' => '5','name' => '58','hex' => NULL],
            ['shop_grid_id' => '5','name' => '60','hex' => NULL],
            ['shop_grid_id' => '6','name' => '1','hex' => NULL],
            ['shop_grid_id' => '6','name' => '2','hex' => NULL],
            ['shop_grid_id' => '6','name' => '3','hex' => NULL],
            ['shop_grid_id' => '6','name' => '4','hex' => NULL],
            ['shop_grid_id' => '6','name' => '5','hex' => NULL],
            ['shop_grid_id' => '6','name' => 'G','hex' => NULL],
            ['shop_grid_id' => '6','name' => 'GG','hex' => NULL],
            ['shop_grid_id' => '6','name' => 'M','hex' => NULL],
            ['shop_grid_id' => '6','name' => 'P','hex' => NULL],
            ['shop_grid_id' => '6','name' => 'PP','hex' => NULL],
            ['shop_grid_id' => '6','name' => 'U','hex' => NULL],
            ['shop_grid_id' => '6','name' => 'XG','hex' => NULL],
            ['shop_grid_id' => '6','name' => 'XGG','hex' => NULL],
            ['shop_grid_id' => '7','name' => '53-54','hex' => NULL],
            ['shop_grid_id' => '7','name' => '55-56','hex' => NULL],
            ['shop_grid_id' => '7','name' => '57-58','hex' => NULL],
            ['shop_grid_id' => '7','name' => '59-60','hex' => NULL],
            ['shop_grid_id' => '7','name' => '61-62','hex' => NULL],
            ['shop_grid_id' => '7','name' => '63-64','hex' => NULL],
            ['shop_grid_id' => '8','name' => '16','hex' => NULL],
            ['shop_grid_id' => '8','name' => '17','hex' => NULL],
            ['shop_grid_id' => '8','name' => '18','hex' => NULL],
            ['shop_grid_id' => '8','name' => '19','hex' => NULL],
            ['shop_grid_id' => '8','name' => '20','hex' => NULL],
            ['shop_grid_id' => '8','name' => '21','hex' => NULL],
            ['shop_grid_id' => '8','name' => '22','hex' => NULL],
            ['shop_grid_id' => '8','name' => '23','hex' => NULL],
            ['shop_grid_id' => '8','name' => '24','hex' => NULL],
            ['shop_grid_id' => '8','name' => '25','hex' => NULL],
            ['shop_grid_id' => '8','name' => '26','hex' => NULL],
            ['shop_grid_id' => '8','name' => '27','hex' => NULL],
            ['shop_grid_id' => '8','name' => '28','hex' => NULL],
            ['shop_grid_id' => '8','name' => '29','hex' => NULL],
            ['shop_grid_id' => '8','name' => '30','hex' => NULL],
            ['shop_grid_id' => '8','name' => '31','hex' => NULL],
            ['shop_grid_id' => '8','name' => '32','hex' => NULL],
            ['shop_grid_id' => '8','name' => '33','hex' => NULL],
            ['shop_grid_id' => '8','name' => '34','hex' => NULL],
            ['shop_grid_id' => '8','name' => '35','hex' => NULL],
            ['shop_grid_id' => '8','name' => '36','hex' => NULL],
            ['shop_grid_id' => '8','name' => '37','hex' => NULL],
            ['shop_grid_id' => '8','name' => '38','hex' => NULL],
            ['shop_grid_id' => '8','name' => '39','hex' => NULL],
            ['shop_grid_id' => '8','name' => '40','hex' => NULL],
            ['shop_grid_id' => '8','name' => '41','hex' => NULL],
            ['shop_grid_id' => '8','name' => '42','hex' => NULL],
            ['shop_grid_id' => '8','name' => '43','hex' => NULL],
            ['shop_grid_id' => '8','name' => '44','hex' => NULL],
            ['shop_grid_id' => '8','name' => '45','hex' => NULL],
            ['shop_grid_id' => '8','name' => '46','hex' => NULL],
            ['shop_grid_id' => '8','name' => '47','hex' => NULL],
            ['shop_grid_id' => '9','name' => '110V','hex' => NULL],
            ['shop_grid_id' => '9','name' => '220V','hex' => NULL],
            ['shop_grid_id' => '2','name' => 'Creme','hex' => '#FFF2CC'],
            ['shop_grid_id' => '2','name' => 'Marrom','hex' => '#B45F06'],
            ['shop_grid_id' => '2','name' => 'Vermelho','hex' => '#FF0000'],
            ['shop_grid_id' => '2','name' => 'Cinza Claro','hex' => '#CCCCCC'],
            ['shop_grid_id' => '2','name' => 'Púrpura','hex' => '#741B47'],
            ['shop_grid_id' => '2','name' => 'Laranja','hex' => '#FF9900'],
            ['shop_grid_id' => '2','name' => 'Fúcsia','hex' => '#E828FF'],
            ['shop_grid_id' => '2','name' => 'Lilás','hex' => '#8E7CC3'],
            ['shop_grid_id' => '2','name' => 'Marrom amarelado','hex' => '#F6B26B'],
            ['shop_grid_id' => '2','name' => 'Ciano escuro','hex' => '#76A5AF'],
            ['shop_grid_id' => '2','name' => 'Verde escuro','hex' => '#38761D'],
            ['shop_grid_id' => '2','name' => 'Rosa','hex' => '#F4CCCC'],
            ['shop_grid_id' => '2','name' => 'Esmeralda','hex' => '#93C47D'],
            ['shop_grid_id' => '2','name' => 'Salmão','hex' => '#EAD1DC'],
            ['shop_grid_id' => '2','name' => 'Verde','hex' => '#0C9800'],
            ['shop_grid_id' => '2','name' => 'Fúcsia escuro','hex' => '#C27BA0'],
            ['shop_grid_id' => '2','name' => 'Dourado','hex' => '#BF9000'],
            ['shop_grid_id' => '2','name' => 'Lavanda','hex' => '#D9D2E9'],
            ['shop_grid_id' => '2','name' => 'Água','hex' => '#83DDFF'],
            ['shop_grid_id' => '2','name' => 'Azul Céu','hex' => '#D0E0E3'],
            ['shop_grid_id' => '2','name' => 'Preto','hex' => '#000000'],
            ['shop_grid_id' => '2','name' => 'Azul','hex' => '#1717FF'],
            ['shop_grid_id' => '2','name' => 'Azul claro','hex' => '#CFE2F3'],
            ['shop_grid_id' => '2','name' => 'Azul aço','hex' => '#6FA8DC'],
            ['shop_grid_id' => '2','name' => 'Vermelho escuro','hex' => '#990000'],
            ['shop_grid_id' => '2','name' => 'Azul escuro','hex' => '#0B5394'],
            ['shop_grid_id' => '2','name' => 'Índigo','hex' => '#351C75'],
            ['shop_grid_id' => '2','name' => 'Branco','hex' => '#FFFFFF'],
            ['shop_grid_id' => '2','name' => 'Branco Navajo','hex' => '#FCE5CD'],
            ['shop_grid_id' => '2','name' => 'Mocassim','hex' => '#FFD966'],
            ['shop_grid_id' => '2','name' => 'Azul petróleo','hex' => '#134F5C'],
            ['shop_grid_id' => '2','name' => 'Amarelo','hex' => '#FFFF00'],
            ['shop_grid_id' => '2','name' => 'Terracota','hex' => '#E06666'],
            ['shop_grid_id' => '2','name' => 'Violeta escuro','hex' => '#7600FF'],
            ['shop_grid_id' => '2','name' => 'Cinza','hex' => '#666666'],
            ['shop_grid_id' => '2','name' => 'Verde claro','hex' => '#D9EAD3'],
            ['shop_grid_id' => '3','name' => 'Creme','hex' => '#FFF2CC'],
            ['shop_grid_id' => '3','name' => 'Marrom','hex' => '#B45F06'],
            ['shop_grid_id' => '3','name' => 'Vermelho','hex' => '#FF0000'],
            ['shop_grid_id' => '3','name' => 'Cinza Claro','hex' => '#CCCCCC'],
            ['shop_grid_id' => '3','name' => 'Púrpura','hex' => '#741B47'],
            ['shop_grid_id' => '3','name' => 'Laranja','hex' => '#FF9900'],
            ['shop_grid_id' => '3','name' => 'Fúcsia','hex' => '#E828FF'],
            ['shop_grid_id' => '3','name' => 'Lilás','hex' => '#8E7CC3'],
            ['shop_grid_id' => '3','name' => 'Marrom amarelado','hex' => '#F6B26B'],
            ['shop_grid_id' => '3','name' => 'Ciano escuro','hex' => '#76A5AF'],
            ['shop_grid_id' => '3','name' => 'Verde escuro','hex' => '#38761D'],
            ['shop_grid_id' => '3','name' => 'Rosa','hex' => '#F4CCCC'],
            ['shop_grid_id' => '3','name' => 'Esmeralda','hex' => '#93C47D'],
            ['shop_grid_id' => '3','name' => 'Salmão','hex' => '#EAD1DC'],
            ['shop_grid_id' => '3','name' => 'Verde','hex' => '#0C9800'],
            ['shop_grid_id' => '3','name' => 'Fúcsia escuro','hex' => '#C27BA0'],
            ['shop_grid_id' => '3','name' => 'Dourado','hex' => '#BF9000'],
            ['shop_grid_id' => '3','name' => 'Lavanda','hex' => '#D9D2E9'],
            ['shop_grid_id' => '3','name' => 'Água','hex' => '#83DDFF'],
            ['shop_grid_id' => '3','name' => 'Azul Céu','hex' => '#D0E0E3'],
            ['shop_grid_id' => '3','name' => 'Preto','hex' => '#000000'],
            ['shop_grid_id' => '3','name' => 'Azul','hex' => '#1717FF'],
            ['shop_grid_id' => '3','name' => 'Azul claro','hex' => '#CFE2F3'],
            ['shop_grid_id' => '3','name' => 'Azul aço','hex' => '#6FA8DC'],
            ['shop_grid_id' => '3','name' => 'Vermelho escuro','hex' => '#990000'],
            ['shop_grid_id' => '3','name' => 'Azul escuro','hex' => '#0B5394'],
            ['shop_grid_id' => '3','name' => 'Índigo','hex' => '#351C75'],
            ['shop_grid_id' => '3','name' => 'Branco','hex' => '#FFFFFF'],
            ['shop_grid_id' => '3','name' => 'Branco Navajo','hex' => '#FCE5CD'],
            ['shop_grid_id' => '3','name' => 'Mocassim','hex' => '#FFD966'],
            ['shop_grid_id' => '3','name' => 'Azul petróleo','hex' => '#134F5C'],
            ['shop_grid_id' => '3','name' => 'Amarelo','hex' => '#FFFF00'],
            ['shop_grid_id' => '3','name' => 'Terracota','hex' => '#E06666'],
            ['shop_grid_id' => '3','name' => 'Violeta escuro','hex' => '#7600FF'],
            ['shop_grid_id' => '3','name' => 'Cinza','hex' => '#666666'],
            ['shop_grid_id' => '3','name' => 'Verde claro','hex' => '#D9EAD3'],
        ];

     }

}
